export const SUPABASE_URL = 'https://uilxtidpetgymkuuwnqk.supabase.co';
export const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpbHh0aWRwZXRneW1rdXV3bnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDU5MDc2MTYsImV4cCI6MjAyMTQ4MzYxNn0.GgV36YJp_bauFu_pQWCcx7NtDtfYsZCnYDToeVEZ484';
